### ISSUE TITLE
Redirect the root url to a homepage

### ISSUE THREAD

**Issue by Pachouuuuuu** [KenticoDevTrev/DynamicRouting#13]
Hi,

It is not a bug but I'm trying to redirect the root page / to another page in my tree. Now I have an error when accessing the url domain.net directly.
How do I override this ?

![image](https://user-images.githubusercontent.com/17520660/70323355-dd617200-182c-11ea-81c5-a8833b1ac2ae.png)

I'm guessing that I have to add a new route but I didn't find the solution. Can you help me with that ?

Thanks for your help.

**Comment by KenticoDevTrev** [comment]
Usually for the "no url" you can either add a blank route and point it to your controller, or add a dynamic route attribute to point the CMS.root to the controller if your choice (just remember the getpage() will return the root in that case so you will need to manually select your home page).
