### ISSUE TITLE
Invalid column name 'IsCustom' when 'Rebuild the Tree (Node Alias Path)'

### ISSUE THREAD

**Issue by rwfresh** [KenticoDevTrev/DynamicRouting#14]
v12.29.6.0 

When attempting to rebuild a subtree treenode an 'Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'IsCustom'.' exception is thrown

-----------------------------
[Exception: 
[DataConnection.HandleError]: 

Query: 
SELECT *
FROM DynamicRouting_UrlSlug
WHERE [UrlSlugNodeID] = @UrlSlugNodeID AND [IsCustom] = @IsCustom

Caused exception: 
Invalid column name 'IsCustom'.
]
-------------------------------

Actual Column name appears to be UrlSlugIsCustom

**Comment by KenticoDevTrev** [comment]
Good catch, probably before I refactored, I'll get it adjusted possibly today, otherwise over the weekend!

**Comment by KenticoDevTrev** [comment]
Resolved in e50c7790a178bc28596cea336b6045251afe8aa7 (Nuget package version 12.29.7).  Please update your nuget packages!
