### ISSUE TITLE
DynamicHttpHandler class does not implement IRequiresSessionState

### ISSUE THREAD

**Issue by thejocus** [KenticoDevTrev/DynamicRouting#15]
As the title mentions, the DynamicHttpHandler class does not implement the IRequiresSessionState interface, which means that the ASP Session is null when within any Dynamically routed controller.

We've created a workaround by creating a custom DynamicHttpHandler class that does implement the missing interface, and a custom DynamicRouteHandler class that returns a new instance of the Custom DynamicHttpHandler. I will submit a pull request shortly.

**Comment by KenticoDevTrev** [comment]
@thejocus good catch, I'll regenerate the nuget package when I get into the office today

**Comment by KenticoDevTrev** [comment]
This has been pushed to NuGet for version 12.29.8, both for the MVC and MVCOnly versions of the Dynamic Routing, you should see it shortly once nuget reindexes, thanks for contributing!
