### ISSUE TITLE
UrlSlug should be included in import/export and synchronisation tasks

### ISSUE THREAD

**Issue by sdolier** [KenticoDevTrev/DynamicRouting#20]
Hi Trev,

When synchronising documents from a staging environment to production, or exporting/importing a site, UrlSlugs are not included. The Urls then need to be manually applied to the destination content.

I think the TYPE_INFO for a UrlSlug should be set to something like:

```
/// <summary>
/// Type information.
/// </summary>
public static readonly ObjectTypeInfo TYPEINFO = new ObjectTypeInfo(typeof(UrlSlugInfoProvider), OBJECT_TYPE, "DynamicRouting.UrlSlug", "UrlSlugID", "UrlSlugLastModified", "UrlSlugGuid", null, "UrlSlug", null, null, "UrlSlugNodeID", "cms.node")
{
    ModuleName = "DynamicRouting.Kentico",
    TouchCacheDependencies = true,
    SupportsCloning = false,
    AllowDataExport = false,
    AllowRestore = false,
    ImportExportSettings =
    {
        IsExportable = true,
        ObjectTreeLocations = new List<ObjectTreeLocation>()
        {
            // Adds the custom class into a new category in the Global objects section of the export tree
            new ObjectTreeLocation(GLOBAL, "Custom"),
        }
    },
    SynchronizationSettings =
    {
        LogSynchronization = SynchronizationTypeEnum.LogSynchronization,
        ObjectTreeLocations = new List<ObjectTreeLocation>()
        {
            // Adds the custom class into a new category in the Global objects section of the staging tree
            new ObjectTreeLocation(GLOBAL, "Custom")
        },
    },
};
```

Cheers, Stephen

**Comment by KenticoDevTrev** [comment]
The url staging tasks were not turned on in purpose because the module should rebuild them as pages are imported.  However thinking in this, are these urls manual/custom ones? Not sure now if I accounted for those.

**Comment by sdolier** [comment]
Hi Trev,

That's right, the custom URLs.

My thoughts were that in a synchronised environment, we would disable the auto url generation task in production and allow it to run on staging. Any changes made by manual editing or the auto generation task in staging could then be synchronised to production.

I'll need to test this, but i also think you can set the info object to touch the parent document when edited and allow the child (urlslug) to be published with the document. so from an editors point of view they are editing a document like any other field and synchronising the changes.

Cheers, Stephen

**Comment by KenticoDevTrev** [comment]
The URL slug generation logic is quite quick, i wouldn't worry about having that run on production.

I will say that it is a royal pain in the butt to include any custom staging task objects with the Document.  Not impossible mind you, but if you look at my Relationships Extended source code, it isn't easy.  Kentico does a lot of stuff with the Document tasks.  That's why i tried to avoid it in these cases.  

That being said, i may have forgotten to test with Custom URL Slugs to see how they work, when i get a little free time i'll run through that scenario.  I believe if that is the case that custom URL slugs don't work because of no staging tasks, i think i can get away with just staging if it becomes custom, or if it become un-customized.

**Comment by KenticoDevTrev** [comment]
Sorry for the delay, i've been more swamped than normal in trying to get a couple key items out the door, i still have it on my radar to add a custom task to handle these custom URL slugs.

**Comment by KenticoDevTrev** [comment]
Making progress.

Commit 17b89cac32fef42d9307673ebddd31b9ad519e36 has the fix, i'm adding one more feature before i make the next nuget package (working on that right now).

Long story short, there were 2 staging bugs.

1. Alternate Urls were not triggering the Page Update, that has been resolved so when you customize / uncustomize or the Url Slug changes, the Alternate Url generated triggers a "Page Update" Properly.

2. As mentioned, Customizing the Url Slug did not stage, it took me about 10 hours of work but i finally got it working properly, so there is a Staging task generated when a Url Slug had custom action placed on it (customize, edit the custom url slug, or un-customize).  These are pushing properly.  You can now also do a mass sync of the Custom url Slugs and it will handle making sure the custom/uncustomized url slugs are handled.  This also forwards the staging task onto other environments properly.

Again it should be in a nuget package, hopefully tonight (march 29th), i just need to add Output Cache dependencies into the system.
