### ISSUE TITLE
Dynamic Routing 

### ISSUE THREAD

**Issue by geoneeliyara** [KenticoDevTrev/DynamicRouting#24]
Hi 

I tried to setup Dynamic Routing on my Kentico 12 MVC project but couldn't succeed on this. Do you have any running example on this? Or would you be able to show an example on Landing Page section in Dancing Goat website. I am confused with the steps 3 & 4 under the heading "Installing on the MVC Site". Would you be able to help me on this

Regards,
Geo

**Comment by KenticoDevTrev** [comment]
My recent blog article on devtrev.com goes through the setup of a basic
site that uses this, although more to come in part two later this month.

But for steps three and four, you don't need to do these steps, they are
just modifying the default behavior through Kentico settings and allowing
not global administrators ui access. Step 5 will be more important. Make
sure your page types have a proper url pattern, {% nodealiaspath %} is the
best.

**Comment by geoneeliyara** [comment]
Hi

I have the url pattern as {%nodealiaspath%} and I rebuild the site as per step 5. I tried the above on Dancing Goat MVC website but i am still getting error while accessing the page. 

The live url still shows http://localhost:51872/Kentico12_DancingGoatMvc_1/en-US/Landing-pages/Coffee-samples . looks like I am missing something. Would you be able to find the issue
 
Regards,
Geo

**Comment by KenticoDevTrev** [comment]
Your site is using a culture prefix, you either need to add these to the
url pattern so the slugs generate with the culture "/{% documentculture%}{%
nodealiaspath%}" , or add event hooks to the dynamic routing global events
to detect the culture from the URL so it can properly remove it from the
actual path to check.

**Comment by geoneeliyara** [comment]
Hi I updated the url pattern as "/{%documentculture%}{%nodealiaspath%}". But i am still getting error while accessing the page. it shows "object ref not found" on  var cultureName = requestContext.RouteData.Values["culture"].ToString();. Sorry to distrub you on this again and again. I didn't really get the full logic behind the dynamic routing.

**Comment by KenticoDevTrev** [comment]
Shoot me an email, tfayas@hbs.net and i'll schedule a screen share to go over it with you.

**Comment by KenticoDevTrev** [comment]
This item is now resolved, it was an issue using the Dancing Goat's system which had the Culture determined in the URL and was not properly catching errors there.  No issue with the module itself.
