### ISSUE TITLE
Need custom error message to get displayed

### ISSUE THREAD

**Issue by shubham1509** [KenticoDevTrev/DynamicRouting#26]
Hello,

Well this is not an issue, just need to know if it is possible.

If the dynamic route is not registered for the page type or if the page is not found, currently for that page type the message displays as follows:

![image](https://user-images.githubusercontent.com/32504972/79238223-bf67e600-7e8c-11ea-8341-02c5c3619355.png)

I want my custom error message or a page like "404" to get displayed. I have tried adding the route:

 // Finally, 404
        routes.MapRoute(
            name: "PageNotFound",
            url: "{*url}",
            defaults: new { controller = "HttpErrors", action = "Index" }
            );

and also added the respective controller for the same. As per my understanding, this controller should have been called if DynamicRouteHandler is not able to find the page for the page type.

May I request, can you please do the needful to let me know, if i am missing something or what could I do more for showing the custom error message?

Thanks

**Comment by KenticoDevTrev** [comment]
Why not add the DynamicRoute() attribute for that class and tell it to go to the HttpErrors controller?
