### ISSUE TITLE
Adding Pages via API page template issue

### ISSUE THREAD

**Issue by shubham1509** [KenticoDevTrev/DynamicRouting#27]
Hello,

I am working on Kentico 12 MVC version 12.0.59 and also installed the dynamic routing (DR) package. The DR package is working fine.

I have created a page type and have registered a page template in MVC.

**Scenario 1 - Adding Pages Manually:** 
When I go to the "Pages" application and try to add a page type manually in the content tree, the page gets added and the page template that I have registered in MVC side, gets successfully applied with the HTML when I see in "Page" tab.

**Scenario 2 - Adding pages via API:** 
Now I am also trying to add a page in the content tree via "Create page API" for Kentico so the pages get added via API. 

The API code is successfully adding the page in the content tree, but when I go to the "Page" tab, its shows the message as in the below screenshot:

![image](https://user-images.githubusercontent.com/32504972/83533704-8acbee80-a50d-11ea-82e9-c308acacbaac.png)

Also I tried debugging the code by applying the debug on the PageTemplateController and it is not getting hit, whereas when I create the page manually the controller method gets hit at the debug point successfully.

API code for adding pages:
![image](https://user-images.githubusercontent.com/32504972/83533806-ab944400-a50d-11ea-9599-00e11675de53.png)

May I request, can you please let me know is it something related to Dynamic routing or is there something I am missing?

Thanks

**Comment by KenticoDevTrev** [comment]
It's possible that you may not have the proper workflow for creating a new page, or you are adding a different page type.

The "No route value found" usually only gets thrown when it does find the page, but the page's class name does not have a Dynamic Route for it.  Are you sure you have the [assembly: DynamicRoute] attribute for the QLS.Individual class?  Can you show me that?

**Comment by shubham1509** [comment]
Hello, 

Thanks for your quick reply. Since I have created a page template so I have used the "[assembly: RegisterPageTemplate()]" for registering the template and not used the " [assembly: DynamicRoute]" attribute.  Please review the code for page template below:

![image](https://user-images.githubusercontent.com/32504972/83538489-84407580-a513-11ea-8a0d-21c9c7bce8bb.png)


As per my understanding, if we have created a page template then any page that is found that has a Page Template will automatically be routed to the Page Template instead of the predetermined Dynamic Routing attribute.

May I request, can you please review and let me know your feedback?

Thanks

**Comment by KenticoDevTrev** [comment]
This makes sense now.  No, when you create a page with the API, it doesn't automatically assign it to a Page Template, it does if you do through the UI.  Dynamic Routing will use the Page Template assigned to a page first, then if no page template is defined it uses it's DynamicRoute attributes to determine where it should go, and if none exists shows that error.

If you want to set a page template with the page creation via API, set the "DocumentPageTemplateConfiguration" property to something like this:

{"identifier":"QLS.PageTemplates.IndividualTemplate","properties":null}

You can do that through this

` newPage.SetValue("DocumentPageTemplateConfiguration", "{\"identifier\":\"QLS.PageTemplates.IndividualTemplate\",\"properties\":null}");`

**Comment by shubham1509** [comment]
Hello Trevor, 

Really Thanks for your help and for the explanation. The above solution worked perfectly!!!! :)

When I create a new page via API the page template is now getting applied and works fine. 

However, just need to confirm for the pages that have been already added via API before applying the above solution and showing the message as "No Dynamic routing tag found", can we somehow update and apply the template for them as well or should I just remove them and again add them,

Can you please let me know?

**Comment by KenticoDevTrev** [comment]
I would add the dynamic route attribute so the page can load with it's layout and then you can switch the page template. You can point the class to a blank view it you wish. Just look at the readme
