### ISSUE TITLE
Multi-Site support

### ISSUE THREAD

**Issue by vhugogarcia** [KenticoDevTrev/DynamicRouting#30]
Hello @KenticoDevTrev ,

First, I would like to thank you for this great package, it helps to reduce the time to implement a dynamic routing on Kentico 12 MVC.

However, I could not find any documentation about multi-site support. I have a website that is planned to have multi-sites for example: 

www.domain.com (Site 1)
test.domain.com (Site 2)
hello.domain.com (Site 3)

I'm wondering how to manage those multi-sites with the dynamic routing package, do you have any idea?.

Thanks in advance,
Victor

**Comment by KenticoDevTrev** [comment]
If you have the latest version of it it is supported, there was a bug in
the previous version with multi site!

**Comment by vhugogarcia** [comment]
Thanks @KenticoDevTrev for the information.
