### ISSUE TITLE
Issue alongside OutputCache attribute

### ISSUE THREAD

**Issue by mattlewis003** [KenticoDevTrev/DynamicRouting#33]
Hi Trev,

Firstly, nice work to date, the routing module has been a huge help.

I've been attempting to use the following output cache attribute above a simple controller action result:
[OutputCache(Duration = 86400, VaryByParam = "nodeAlias", Location = OutputCacheLocation.Server)]

This works fine for the most part, but I've found that if I view the resulting page/action result on the front end website and then jump into the CMS and attempt to use the page builder on that same page, that the output cache appears to take over and serves the static page, and the page editor is disabled.

I had opened a support ticket with Kentico but Juraj did some investigation and seemed to think it was related to the dynamic routing module. I've copied his findings below just in case they help at all:

I took a closer look at the dynamic routing module - my intention was to see how "easy" it is to remove from the project. It is not that easy....but I was checking the settings and how it is being installed into Kentico, to see if everything is OK. When reading the instructions, there was a mention to rebuild the URL slugs - so I tried it and guess what - after this I was able to reproduce the issue. Then, when I clear the Kentico's cache in System app, things are working normal until I visited the page on the live site. So, there is something not right with the dynamic routing module. When I initially restored the backups, I did not had the matching URL slugs for this module so everything worked fine. The dynamic routing is probably not recognizing the preview/edit mode inside Kentico app correctly and serves the cached version of the page.

**Comment by KenticoDevTrev** [comment]
One issue may be your custom vary by. Output caching by default caches on
the url, so the preview url and live url are different (the edit/preview
starts with /cmsx or something).

Try removing the vary by?

**Comment by mattlewis003** [comment]
Certainly seems to be working having removed the VaryByParam, haven't been able to reproduce the issue without it. 

Thanks for the help.

**Comment by KenticoDevTrev** [comment]
No problem!
