### ISSUE TITLE
Url Conflict Issue

### ISSUE THREAD

**Issue by rcisneros138** [KenticoDevTrev/DynamicRouting#34]
Hi there,

I have Integrated this package into a client's Kentico 12 MVC project and am having an odd issue I can't seem to resolve. I have set each page type to have a URL pattern of "/{% DocumentCulture %}{% NodeAliasPath %}". However, when the url is generated (even after using "clear and rebuild" within the Dynamic Routing app) each url beyond the root element is given an postfix which indicates a url slug conflict. 

My understanding is the slugs are generated based off of the URL pattern. The NodeAliasPath also seems to be unique for each page type which is having this issue.

Any guidance would be greatly appreciated.

Raymond

**Comment by KenticoDevTrev** [comment]
Hmmm it should work, would you email me at tfayas@gmail.com with what days and times you would be available for a screen share?

**Comment by rcisneros138** [comment]
Apologies for the late reply. It looks like this was caused by a timeout between kentico and out Azure database. A Kentico hotfix, which included support for controlling batch sizes seems to have solved the Issue.
