### ISSUE TITLE
VirtualContextHashOrUserValidationFailed after upgrade to Kentico 12.0.19

### ISSUE THREAD

**Issue by stephenr85** [KenticoDevTrev/DynamicRouting#37]
​We have just applied the 12.0.91 hotfixes to our 12.0.68 instance, and everything appears to be working normally in the Kentico Admin and on one of the sites.

A second site is working normally on its presentation URL, but preview URLs in the Kentico Admin are all showing a 404 response with the attached error in the Event Log.
[eventdetails-HGACBuy-preview-error.txt](https://github.com/KenticoDevTrev/DynamicRouting/files/5616842/eventdetails-HGACBuy-preview-error.txt)

I have confirmed that the CMSHashStringSalt​ application keys match on the Kentico and MVC instances, and I've resigned all macro signatures via System > Macros > Signatures, and I've run Dynamic Routing > Rebuild Site, but I am still getting the 404 responses (again, only on one site) with the VirtualContextHashOrUserValidationFailed  error in the Event Log.

**Comment by KenticoDevTrev** [comment]
Hmm, this doesn't look to be related to Dynamic Routing i'm afriad, that's the preview URL which doesn't even use Dynamic Routing.  

Can you check the solutions here?
https://devnet.kentico.com/articles/kentico-12-mvc-page-preview-404-errors-troubleshooting-tips

**Comment by stephenr85** [comment]
Thanks, Trevor. I'm not sure what did it, exactly, but it started working while I was trying various things to troubleshoot. Based on the article you provided, it must have had something to do with restoring the nuget packages, despite having already upgraded the Kentico nuget packages in my MVC app to match the admin instance. 

I tested it after each package reinstall as well as the Restore Nuget Packages feature in Visual Studio, but it didn't actually start working until I noticed the bin directory was somehow included in the csproj and excluded it.

On another note, I tried to get to your site and got a 503 error.
![image](https://user-images.githubusercontent.com/976179/100931610-5fbc5a80-34b0-11eb-9c24-061f76db462f.png)

**Comment by KenticoDevTrev** [comment]
Glad it's working, i restarted the devtrev.com site, sadly it's on an old crappy host, i need to rebuild it in .net core but i still need to finish upgrading my modules, remaking the community baseline project in .net core, get my other site rebuilt....so probably sometime next decade :P

**Comment by stephenr85** [comment]
I hear ya! Good luck. Thanks for the work you've done for the community thus far.
