### ISSUE TITLE
/CMSModules/DynamicRouting.Kentico/QuickOperations.aspx security

### ISSUE THREAD

**Issue by lightfire** [KenticoDevTrev/DynamicRouting#39]
Hi,
thanks for the great module,

Everyone which access admin UI, even editor roles can access page "`/CMSModules/DynamicRouting.Kentico/QuickOperations.aspx` "
I Assumed that Restrictions not controlled by QuickOperations.aspx, for security scans this issue returned to unauthorized access to page.

Adding UI restrictions not  enough for user who knows url,
Checking CurrentUser permission is more suitable on page Load event like other Admin pages?

**Comment by KenticoDevTrev** [comment]
Good point, I did forget to add security in it, I'll try to get that on there.

**Comment by KenticoDevTrev** [comment]
Fixed in release 12.29.20
