### ISSUE TITLE
Alternative Url auto generated

### ISSUE THREAD

**Issue by massimde** [KenticoDevTrev/DynamicRouting#41]
Hi,
I noticed that: when a page is renamed, the UrlSlug_Update_Before_301Redirect generates an alternative URL that doesn’t matches the URL Slug and doesn’t contains the culture code as well.

I would like to prevent this automatic behavior:  is it possible?

**Comment by KenticoDevTrev** [comment]
I don't currently have a hook or setting to remove this behavior, it should
generate the previous url slug as an alias, is this not the case? Can you
screenshot the alternate url screen after you make a change?

**Comment by massimde** [comment]
After changing the url pattern and clearing the cache, the problem no longer occurred. It would be useful to have the possibility to deactivate this automatism.
