### ISSUE TITLE
Staging Module Doesn't work

### ISSUE THREAD

**Issue by chamarajanaka** [KenticoDevTrev/DynamicRouting#42]
Hi,

We are using Dynamic Routing module in our project but now the Kentico staging sync doesn't work.  Please see my StackOverflow post
https://stackoverflow.com/questions/68948416/kentico-staging-sync?noredirect=1#comment121894549_68948416

Thanks,
Chamara

**Comment by KenticoDevTrev** [comment]
I think Dmitry comment is correct, nothing wrong with the module, I think you have the staging server pointing to the mvc site when you need to point to the admin url of the other environment
