### ISSUE TITLE
Support for Kentico 13

### ISSUE THREAD

**Issue by chamarajanakaenote** [KenticoDevTrev/DynamicRouting#58]
Does this support Kentico 13. When I try to install via nuget it prompts to install Kentico.AspNet.Mvc.Libraries version 12.0.79 which I don't won't to install becuase I already have the version 13.0.98 installed.

**Comment by seangwright** [comment]
@chamarajanakaenote Kentico Xperience 13 supports Content Tree Based Routing as part of the product

https://docs.xperience.io/developing-websites/implementing-routing/content-tree-based-routing

**Comment by KenticoDevTrev** [comment]
As you probably noted (due to the close), and as Sean pointed out, it's been replaced with Kentico's built in system.  I worked with Kentico to make sure transition would be smooth.

Please see the "Note on Upgrading to Kentico Xperience 13" on the readme for instructions on migrating!
