### ISSUE TITLE
Can't insert null into column TaskData in the CMS_ScheduledTask table

### ISSUE THREAD

**Issue by reyonlines** [KenticoDevTrev/DynamicRouting#8]
Hi Trevor,

I just installed the package DynamicRouting.Kentico 12.29.0 but it make the application crash with error: Cannot insert the value NULL into column 'TaskData', table 'DancingGoatMvcIIS.dbo.CMS_ScheduledTask'; column does not allow nulls. INSERT fails.
The statement has been terminated.
![image](https://user-images.githubusercontent.com/1857559/68710297-3fe48c80-0565-11ea-8ea2-61241f2a1772.png)

**Comment by KenticoDevTrev** [comment]
Let me quickly regenerate a new nuget package, one thing i didn't test was
the creation of the scheduled tasks, give me a moment!

**Comment by KenticoDevTrev** [comment]
Alright, got it resolved, repackaging nuggets....

**Comment by reyonlines** [comment]
Hi Trevor,

Thank you so much for the quick response. I just installed package
DynamicRouting.Kentico.MVC 12.29.0 and it has the same problem.

Thanks,
Rey

**Comment by KenticoDevTrev** [comment]
Fixed with fc621244b8704bad55d9473718e50c4a5aa41c11, the 12.29.2 packages for both Mother and MVC should be available shortly once they are indexed!

**Comment by KenticoDevTrev** [comment]
If you still get these emails Reyonline, shoot me a message at tfayas@hbs.net on how the install goes, now that that one thing is fixed, i'm always looking for trouble points people may have.

**Comment by rwfresh** [comment]
Hi @reyonlines did you resolve this issue? @KenticoDevTrev I just installed the latest package to my CMS and upon first run after install I am receiving the same error. Thanks for your help.

**Comment by KenticoDevTrev** [comment]
Should be there on the latest versions, I'll double check when I get home

**Comment by KenticoDevTrev** [comment]
@rwfresh  Everything looks correct, i just checked the .dll of the 12.29.6 and this is what it has for the task:

```
if (TaskInfoProvider.GetTasks().WhereEquals("TaskName", "CheckUrlSlugQueue").get_Count() == 0)
            {
                TaskInfo taskInfo = new TaskInfo();
                taskInfo.set_TaskName("CheckUrlSlugQueue");
                taskInfo.set_TaskDisplayName("Dynamic Routing - Check Url Slug Generation Queue");
                taskInfo.set_TaskAssemblyName("DynamicRouting.Kentico");
                taskInfo.set_TaskClass("DynamicRouting.Kentico.DynamicRouteScheduledTasks");
                taskInfo.set_TaskInterval("hour;11/3/2019 4:54:30 PM;1;00:00:00;23:59:00;Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday");
                taskInfo.set_TaskDeleteAfterLastRun(false);
                taskInfo.set_TaskRunInSeparateThread(true);
                taskInfo.set_TaskAllowExternalService(true);
                taskInfo.set_TaskUseExternalService(false);
                taskInfo.set_TaskRunIndividuallyForEachSite(false);
                taskInfo.set_TaskEnabled(true);
                taskInfo.set_TaskData("");
                TaskInfoProvider.SetTaskInfo(taskInfo);
            }
```
As you can see, the TaskData is being set to an empty string (not null), 

Can you verify the .dll version of the DynamicRouting.Kentico.Base.dll and see if the version is correct?

Also try reinstalling the nuget package.  If neither work and it's still giving an error, email me and we'll schedule a screen share.  A lot of people have downloaded and installed and it's odd only you are having this issue after the fix...

**Comment by KenticoDevTrev** [comment]
@rwfresh  just in case i added a try/catch around it for the new version (fixing the other open issue you posted), so either way this should be resolved by updating your nuget package, although check your event log after and see if it shows an error creating the scheduled task itself... if so it has instructions to create it manually.
